services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - D:/docker-data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis-cache
    restart: always
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - D:/docker-data/redis:/data

  scanner:
    build:
      context: ./microservice-scanner
    container_name: python-ext-scanner
    restart: always
    ports:
      - "8000:8000"
