import type { Device } from "@/components/devicestable";
import type { ChartConfig } from "@/components/ui/chart";
import { Wifi, SquareTerminal, Gauge, Settings2, Laptop, FileText, Brain, History, CircleAlert } from "lucide-react";

export const sidebarNavs = {
  user: {
    name: "Admin",
    email: "netdetect@example.com",
    avatar: "https://avatars.githubusercontent.com/u/163083905?v=4",
  },
  team: {
    name: "Netdetect",
    logo: Wifi,
    plan: "Capstone System",
  },
  sidebarNavsMain: [
    {
      title: "Dashboard",
      url: "/dashboard",
      icon: SquareTerminal,
    },
    {
      title: "Devices",
      icon: Laptop,
      url: "/devices",
      items: [
        { title: "All Devices", url: "/devices/all" },
        { title: "Whitelist/Blacklist", url: "/devices/whitelist-blacklist" },
      ],
    },
    {
      title: "Bandwidth Usage",
      icon: Gauge,
      url: "/bandwidth-usage",
      items: [
        { title: "Overview", url: "/bandwidth-usage/overview" },
        { title: "Per Device", url: "/bandwidth-usage/per-device" },
      ],
    },
    {
      title: "ISP Status",
      url: "/isp-status",
      icon: Wifi,
    },
    {
      title: "AI Insights",
      url: "/ai-insights",
      icon: Brain,
    },

  ],
  sidebarNavsSecond: [
    {
      title: "Access Logs",
      url: "/logs",
      icon: History,
    },
    {
      title: "Reports",
      url: "/reports",
      icon: FileText,
    },
    {
      title: "Alerts",
      url: "/alerts",
      icon: CircleAlert,
    },
    {
      title: "Settings",
      url: "/settings",
      icon: Settings2,
    },
  ]
};

export const chartConfig = {
  visitors: {
    label: "Visitors",
  },
  chrome: {
    label: "Chrome",
    color: "var(--chart-1)",
  },
  safari: {
    label: "Safari",
    color: "var(--chart-2)",
  },
  firefox: {
    label: "Firefox",
    color: "var(--chart-3)",
  },
  edge: {
    label: "Edge",
    color: "var(--chart-4)",
  },
  other: {
    label: "Other",
    color: "var(--chart-5)",
  },
} satisfies ChartConfig

export const devices: Device[] = [
  {
    uid: 1,
    name: "Rendyll-PC",
    hostname: "rendyll-pc.local",
    ip: "192.168.1.10",
    mac: "A0:98:05:12:34:56",
    signal: 82,
    status: "Online",
    type: "Desktop",
    os: "Windows 11",
    download: 45.6,
    upload: 18.2,
    ping: 8,
    authorized: true,
    blocked: false,
  },
  {
    uid: 2,
    name: "Phone",
    hostname: "phone.local",
    ip: "192.168.1.11",
    mac: "9C:B6:D0:65:43:21",
    signal: 60,
    status: "Offline",
    type: "Mobile",
    os: "Android",
    download: 0,
    upload: 0,
    ping: 0,
    authorized: true,
    blocked: false,
  },
  {
    uid: 3,
    name: "Laptop",
    hostname: "laptop.local",
    ip: "192.168.1.12",
    mac: "7A:88:F0:34:12:AB",
    signal: 75,
    status: "Online",
    type: "Laptop",
    os: "macOS",
    download: 32.1,
    upload: 9.4,
    ping: 12,
    authorized: true,
    blocked: false,
  },
  {
    uid: 4,
    name: "Smart TV",
    hostname: "smarttv.local",
    ip: "192.168.1.13",
    mac: "5B:C4:9E:11:22:33",
    signal: 70,
    status: "Online",
    type: "TV",
    os: "Tizen",
    download: 20.5,
    upload: 3.1,
    ping: 14,
    authorized: false,
    blocked: true,
  },
  {
    uid: 5,
    name: "Tablet",
    hostname: "tablet.local",
    ip: "192.168.1.14",
    mac: "00:1A:2B:3C:4D:5E",
    signal: 65,
    status: "Online",
    type: "Tablet",
    os: "iOS",
    download: 12.8,
    upload: 5.6,
    ping: 20,
    authorized: true,
    blocked: false,
  },
  {
    uid: 6,
    name: "Printer",
    hostname: "printer.local",
    ip: "192.168.1.15",
    mac: "11:22:33:44:55:66",
    signal: 40,
    status: "Offline",
    type: "Peripheral",
    os: "Embedded",
    download: 0,
    upload: 0,
    ping: 0,
    authorized: true,
    blocked: false,
  },
  {
    uid: 7,
    name: "Security Camera",
    hostname: "cam1.local",
    ip: "192.168.1.16",
    mac: "AA:BB:CC:DD:EE:FF",
    signal: 55,
    status: "Online",
    type: "Camera",
    os: "Custom",
    download: 5.2,
    upload: 2.1,
    ping: 25,
    authorized: false,
    blocked: true,
  },
  {
    uid: 8,
    name: "Echo Dot",
    hostname: "echo.local",
    ip: "192.168.1.17",
    mac: "33:44:55:66:77:88",
    signal: 78,
    status: "Online",
    type: "Speaker",
    os: "AlexaOS",
    download: 3.4,
    upload: 1.2,
    ping: 18,
    authorized: true,
    blocked: false,
  },
  {
    uid: 9,
    name: "Raspberry Pi",
    hostname: "raspberry.local",
    ip: "192.168.1.18",
    mac: "00:11:22:33:44:55",
    signal: 69,
    status: "Online",
    type: "IoT",
    os: "Linux",
    download: 9.8,
    upload: 2.3,
    ping: 10,
    authorized: true,
    blocked: false,
  },
  {
    uid: 10,
    name: "Office-PC",
    hostname: "office.local",
    ip: "192.168.1.19",
    mac: "AA:11:BB:22:CC:33",
    signal: 58,
    status: "Offline",
    type: "Desktop",
    os: "Windows 10",
    download: 0,
    upload: 0,
    ping: 0,
    authorized: true,
    blocked: false,
  },
  {
    uid: 11,
    name: "Gaming Laptop",
    hostname: "gamer.local",
    ip: "192.168.1.20",
    mac: "CC:DD:EE:FF:11:22",
    signal: 80,
    status: "Online",
    type: "Laptop",
    os: "Windows 11",
    download: 55.7,
    upload: 24.8,
    ping: 6,
    authorized: true,
    blocked: false,
  },
  {
    uid: 12,
    name: "iPhone",
    hostname: "iphone.local",
    ip: "192.168.1.21",
    mac: "AB:CD:EF:12:34:56",
    signal: 85,
    status: "Online",
    type: "Mobile",
    os: "iOS",
    download: 30.2,
    upload: 11.7,
    ping: 9,
    authorized: true,
    blocked: false,
  },
  {
    uid: 13,
    name: "NAS Storage",
    hostname: "nas.local",
    ip: "192.168.1.22",
    mac: "66:77:88:99:AA:BB",
    signal: 62,
    status: "Online",
    type: "Storage",
    os: "Linux",
    download: 60.0,
    upload: 45.3,
    ping: 5,
    authorized: true,
    blocked: false,
  },
  {
    uid: 14,
    name: "Google Home",
    hostname: "googlehome.local",
    ip: "192.168.1.23",
    mac: "12:34:56:78:9A:BC",
    signal: 73,
    status: "Online",
    type: "Speaker",
    os: "Fuchsia",
    download: 2.9,
    upload: 1.1,
    ping: 22,
    authorized: false,
    blocked: false,
  },
  {
    uid: 15,
    name: "Old Phone",
    hostname: "oldphone.local",
    ip: "192.168.1.24",
    mac: "98:76:54:32:10:FF",
    signal: 30,
    status: "Offline",
    type: "Mobile",
    os: "Android",
    download: 0,
    upload: 0,
    ping: 0,
    authorized: false,
    blocked: false,
  },
  {
    uid: 16,
    name: "Doorbell Cam",
    hostname: "doorbell.local",
    ip: "192.168.1.25",
    mac: "01:23:45:67:89:AB",
    signal: 67,
    status: "Online",
    type: "Camera",
    os: "Custom",
    download: 2.3,
    upload: 0.9,
    ping: 30,
    authorized: true,
    blocked: false,
  },
  {
    uid: 17,
    name: "Workstation",
    hostname: "ws1.local",
    ip: "192.168.1.26",
    mac: "DE:AD:BE:EF:12:34",
    signal: 90,
    status: "Online",
    type: "Desktop",
    os: "Linux",
    download: 78.4,
    upload: 34.7,
    ping: 4,
    authorized: true,
    blocked: false,
  },
  {
    uid: 18,
    name: "Kitchen Display",
    hostname: "kitchen.local",
    ip: "192.168.1.27",
    mac: "EF:CD:AB:89:67:45",
    signal: 50,
    status: "Offline",
    type: "Display",
    os: "Android",
    download: 0,
    upload: 0,
    ping: 0,
    authorized: false,
    blocked: true,
  },
  {
    uid: 19,
    name: "WiFi Extender",
    hostname: "extender.local",
    ip: "192.168.1.28",
    mac: "BE:EF:CA:FE:12:00",
    signal: 76,
    status: "Online",
    type: "Repeater",
    os: "Embedded",
    download: 10.2,
    upload: 2.0,
    ping: 11,
    authorized: true,
    blocked: false,
  },
  {
    uid: 20,
    name: "Backup Server",
    hostname: "backup.local",
    ip: "192.168.1.29",
    mac: "FE:ED:FA:CE:88:99",
    signal: 72,
    status: "Online",
    type: "Server",
    os: "FreeBSD",
    download: 120.5,
    upload: 88.3,
    ping: 3,
    authorized: true,
    blocked: false,
  }
]
