export const routes: Record<string, string> = {
    "/dashboard": "Dashboard",
    "/devices": "All Devices",
    "/devices/all": "All Devices",
    "/devices/whitelist-blacklist": "Whitelist/Blacklist",
    "/bandwidth-usage": "Bandwidth Usage Overview",
    "/bandwidth-usage/overview": "Bandwidth Usage Overview",
    "/bandwidth-usage/per-device": "Bandwidth Usage Per Device",
    "/isp-status": "ISP Status",
    "/settings": "Settings",
    "/logs": "Access Logs",
    "/reports": "Reports",
    "/alerts": "Alerts",
    "/ai-insights": "AI Insights",
    "/web-filtering": "Web Filtering",
    "/web-filtering/overview": "Web Filtering",
}
