export const routes: Record<string, string> = {
    "/dashboard": "Main Dashboard",
    "/devices": "Devices Page",
    "/devices/all": "Devices Page",
    "/devices/whitelist-blacklist": "Whitelist/Blacklist Page",
    "/bandwidth-usage": "Bandwidth Usage Overview Page",
    "/bandwidth-usage/overview": "Bandwidth Usage Overview Page",
    "/bandwidth-usage/per-device": "Bandwidth Usage Per Device Page",
    "/bandwidth-usage/shaper": "Bandwidth Shaper Page",
    "/isp-status": "ISP Status Page",
    "/settings": "Reports Page",
    "/logs": "Access Logs",
    "/reports": "Reports",
    "/alerts": "Alerts & Notifications",
    "/ai-insights": "AI Insights Page",
    "/web-filtering": "Web Control Page",
}
